### ISSUE TITLE
XCode build fails during Firebase setup

### ISSUE THREAD

**Issue by arnaugomez** [mrmilu/flutter_base#33]
## Environment

**Package version:** 0.0.1+202304051  
**Platform:** iOS 
**Device information:** iPhone SE Simulator  

## Description
This was a very frequent bug in a project that used the `react_base` (Imaweb). It was fixed by Adri, and now I want to apply the fix to the react_base.

**Expected behavior:**
XCode compilation is successful

**Current behavior:**
App does not compile (see stack trace below)

## Steps to reproduce

1. Run app with Xcode 15.1 iPhone SE Simulator

## Stacktrace/Logcat   
```
Launching lib/main_dev.dart on iPhone SE (3rd generation) in debug mode...
main_dev.dart:1
Xcode build done.                                           56.2s
Failed to build iOS app
Error (Xcode): Build input file cannot be found: '/Users/arnau/Desktop/work/flutter_base/ios/Runner/GoogleService-Info.plist'. Did you forget to declare this file as an output of a script phase or custom build rule which produces it?

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).
```

**Comment by arnaugomez** [comment]
This bug was fixed in the Imaweb project but it is not fixed here. I am going to make a PR that fixes this bug.

**Comment by hazzo** [comment]
@arnaugomez what is the bug?. GoogleServices-Info.plist are not supposed to be uploaded here because this is a public repository.
